theme: jekyll-theme-minimal
title: Snippet Shortcodes
description: Technical documentation for the WordPress plugin Snippet Shortcodes.
baseurl: /
logo: assets/images/product-logo.png
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
port: 9000